### ISSUE TITLE
Unclear about parameters in  ephemeris.getAllPlanets()

### ISSUE THREAD

**Issue by andreas-groos** [hemantgoswami/ephemeris#1]
Hi,

I'm not familiar with the ephemeris but need it for a project of a client. What are the parameters in ephemeris.getAllPlanets, i.e. (dateObj, lat?, lng?, number? (0 in the code example)). Is is lat, lng or lng, lat.

Thanks a lot, would be good to have a but a listing of the parameters in the README.

Andreas

**Comment by hemantgoswami** [comment]
Hello Andreas,

parameters are as follows: ephemeris.getAllPlanets(dateObj, longitude, latitude, height)

Thanks for raising this, I'll update the documentation soon.
If your query is resolved, please close the issue.

Regards,
Hemant

**Comment by hemantgoswami** [comment]
documentation updated
