### ISSUE TITLE
Facing trouble in npm install on Windows system

### ISSUE THREAD

**Issue by Ankit-Gupta-1511** [hemantgoswami/ephemeris#3]
Please I really need this for a project, I am not able to install this package with npm

**Comment by hemantgoswami** [comment]
> Please I really need this for a project, I am not able to install this package with npm

I have upgraded a few files and can test it locally for it to work correctly.

Have package installed using command `npm i ephemeris moment-timezone` if you are using npm or `yarn add ephemeris moment-timezone` if using yarn

and after that in one of your JS files run the code below and it should work.

```
const ephemeris = require('ephemeris');
const Moment = require('moment-timezone');
const dateObj = new Moment.tz('10.08.2015 17:09:01', 'DD.MM.YYYY HH:mm:ss', 'UTC')

// parameters: ephemeris.getAllPlanets(dateObj, longitude, latitude, height);
var result = ephemeris.getAllPlanets(dateObj, 10.0014, 53.5653, 0);
```

**Comment by Ankit-Gupta-1511** [comment]
Thank you so much for your effort. But still, there's an issue with npm but yarn add works. Thanks again.

```
$ npm i ephemeris moment-timezone --save

> ephemeris@2.0.0 postinstall F:\emm-backend\backend\node_modules\ephemeris
> scripts/build.js

'scripts' is not recognized as an internal or external command,
operable program or batch file.
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN strapi-connector-bookshelf@3.0.0-beta.20.3 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ephemeris@2.0.0 postinstall: `scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ephemeris@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ankit\AppData\Roaming\npm-cache\_logs\2020-07-07T07_49_28_618Z-debug.log
```

**Comment by hemantgoswami** [comment]
> Thank you so much for your effort. But still, there's an issue with npm but yarn add works. Thanks again.
> 
> ```
> $ npm i ephemeris moment-timezone --save
> 
> > ephemeris@2.0.0 postinstall F:\emm-backend\backend\node_modules\ephemeris
> > scripts/build.js
> 
> 'scripts' is not recognized as an internal or external command,
> operable program or batch file.
> npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
> npm WARN strapi-connector-bookshelf@3.0.0-beta.20.3 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ephemeris@2.0.0 postinstall: `scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ephemeris@2.0.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Ankit\AppData\Roaming\npm-cache\_logs\2020-07-07T07_49_28_618Z-debug.log
> ```

Dear Ankit,

The error regarding unrecognized `script` is due to the fact there's an error either in your npm cache or you have a quite old version of npm running. I can confirm this works with the command you specified.

```
hemant  ~/projects/test  npm i ephemeris moment-timezone --save

> ephemeris@2.0.0 postinstall /Users/goswamih/projects/test/node_modules/ephemeris
> scripts/build.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ moment-timezone@0.5.31
+ ephemeris@2.0.0
added 3 packages from 7 contributors and audited 3 packages in 1.644s
found 0 vulnerabilities
```

if clearing cache or reinstalling npm does not work, then I'd suggest looking on web for your environment specific solution:
`https://www.google.com/search?q=%27scripts%27+is+not+recognized+as+an+internal+or+external+command&oq=%27scripts%27+is+not+recognized+as+an+internal+or+external+command&aqs=chrome..69i57.255j0j7&sourceid=chrome&ie=UTF-8`

Regards,
Hemant

**Comment by Ankit-Gupta-1511** [comment]
Ok, I figured out the problem. It's a windows specific issue(even after upgrading npm and clearing cache). On my Linux machine it's working perfectly fine. Thanks
